#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] && exit 0
if [ -f /etc/uci-defaults/30_luci-theme-pixel ]; then
	( . /etc/uci-defaults/30_luci-theme-pixel ) && rm -f /etc/uci-defaults/30_luci-theme-pixel
fi
rm -rf /tmp/luci-indexcache* /tmp/luci-modulecache
exit 0
